import crypto from 'crypto';
import type { SessionStorage } from './storage.js';
import type { Session, SessionMessage, SessionFilters, SessionChunk } from './types.js';
import type { VectorStore, VectorFilter } from '../vector/vector-store.js';
import type { EmbeddingProvider } from '../embedding/provider.js';
import type { OllamaLlmClient } from '../llm/ollama.js';
import { chunkMessage } from './chunking.js';
import logger from '../logger.js';

/** Generate a deterministic UUID v5 from message ID + chunk index */
function chunkPointId(messageId: string, chunkIndex: number): string {
  const hash = crypto.createHash('sha1').update(`${messageId}:${chunkIndex}`).digest('hex');
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-${hash.slice(12, 16)}-${hash.slice(16, 20)}-${hash.slice(20, 32)}`;
}

export class SessionManager {
  private processing = false;
  private workerInterval: ReturnType<typeof setInterval> | null = null;

  constructor(
    private storage: SessionStorage,
    private vectorStore?: VectorStore,
    private embeddingProvider?: EmbeddingProvider,
    private llmClient?: OllamaLlmClient,
  ) {}

  /**
   * Import session — saves to PG immediately, queues LLM + embedding for background processing.
   * Returns instantly (~2-3 sec) regardless of session size.
   */
  async importSession(agentTokenId: string, data: {
    externalId?: string;
    name?: string;
    summary?: string;
    projectId?: string;
    workingDirectory?: string;
    gitBranch?: string;
    tags?: string[];
    startedAt?: string;
    endedAt?: string;
    messages: Array<{ role: string; content: string; timestamp?: string; toolNames: string[] }>;
  }): Promise<Session> {
    // Check duplicate
    if (data.externalId) {
      const existing = await this.storage.findByExternalId(agentTokenId, data.externalId);
      if (existing) return existing;
    }

    // If summary provided by client, use it; otherwise mark for LLM generation
    const summary = data.summary || 'Pending summarization...';
    const needsSummary = !data.summary;

    const session = await this.storage.createSession({ agentTokenId, ...data, summary });

    // Set status to 'queued' — background worker will process LLM + embedding
    await this.storage.updateEmbeddingStatus(session.id, needsSummary ? 'queued' : 'queued_embed');

    logger.info({ sessionId: session.id, messageCount: session.messageCount, needsSummary },
      'Session imported, queued for processing');

    return session;
  }

  /**
   * Background worker: processes one queued session at a time.
   * Call via setInterval — safe to call concurrently (uses lock flag).
   */
  async processQueue(): Promise<void> {
    if (this.processing) return; // Already processing one
    this.processing = true;

    try {
      // Find next queued session
      const session = await this.storage.getNextQueued();
      if (!session) return;

      logger.info({ sessionId: session.id, status: session.embeddingStatus }, 'Processing queued session');

      // Step 1: LLM summarization (if needed)
      if (session.embeddingStatus === 'queued') {
        await this.storage.updateEmbeddingStatus(session.id, 'summarizing');

        const messages = await this.storage.getMessages(session.id, 0);

        if (this.llmClient?.isReady()) {
          try {
            const summary = await this.llmClient.summarizeSession(
              messages.map(m => ({ role: m.role, content: m.content })),
            );
            await this.storage.updateSummary(session.id, summary);
            const updated = await this.storage.getSession(session.id);
            if (updated) Object.assign(session, updated);
            logger.info({ sessionId: session.id }, 'Session summary generated by LLM');
          } catch (err) {
            logger.warn({ err, sessionId: session.id }, 'LLM summarization failed, using fallback');
          }
        }

        // If summary is still the placeholder, use fallback from first user message
        if (session.summary === 'Pending summarization...') {
          const firstUser = messages.find(m => m.role === 'user');
          const fallback = firstUser
            ? (firstUser.content.length > 200 ? firstUser.content.slice(0, 200) + '...' : firstUser.content)
            : 'Imported session';
          await this.storage.updateSummary(session.id, fallback);
          session.summary = fallback;
        }

        await this.storage.updateEmbeddingStatus(session.id, 'embedding');
      } else {
        // queued_embed — summary already provided, skip to embedding
        await this.storage.updateEmbeddingStatus(session.id, 'embedding');
      }

      // Step 2: Embedding (summary + messages → Qdrant)
      if (this.embeddingProvider?.isReady() && this.vectorStore) {
        try {
          await this.embedSession(session);
          await this.storage.updateEmbeddingStatus(session.id, 'complete');
          logger.info({ sessionId: session.id }, 'Session embedding complete');
        } catch (err) {
          await this.storage.updateEmbeddingStatus(session.id, 'failed');
          logger.error({ err, sessionId: session.id }, 'Session embedding failed');
        }
      } else {
        // No embedding provider — mark as complete without vectors
        await this.storage.updateEmbeddingStatus(session.id, 'complete');
        logger.info({ sessionId: session.id }, 'Session complete (no embedding provider)');
      }
    } finally {
      this.processing = false;
    }
  }

  /**
   * Start background worker — processes queued sessions every N seconds.
   */
  async startWorker(intervalSec: number = 30): Promise<void> {
    if (this.workerInterval) return;

    // Recovery: reset any sessions stuck in transient states from a previous crash
    await this.storage.recoverStuckSessions();

    this.workerInterval = setInterval(() => {
      this.processQueue().catch(err =>
        logger.error({ err }, 'Session queue worker error'),
      );
    }, intervalSec * 1000);

    // Also run immediately on start
    this.processQueue().catch(err =>
      logger.error({ err }, 'Session queue worker initial run error'),
    );

    logger.info({ intervalSec }, 'Session queue worker started');
  }

  stopWorker(): void {
    if (this.workerInterval) {
      clearInterval(this.workerInterval);
      this.workerInterval = null;
    }
  }

  private async embedSession(session: Session): Promise<void> {
    const agentTokenId = session.agentTokenId;

    // 1. Embed summary → sessions collection
    const summaryVector = await this.embeddingProvider!.embed(session.summary, 'document');
    await this.vectorStore!.upsert('sessions', session.id, summaryVector, {
      session_id: session.id,
      agent_token_id: agentTokenId,
      project_id: session.projectId ?? '',
      name: session.name ?? '',
      tags: session.tags,
      started_at: session.startedAt ? new Date(session.startedAt).getTime() : 0,
      message_count: session.messageCount,
    });

    // 2. Chunk and embed messages → session_messages collection
    const dbMessages = await this.storage.getMessages(session.id, 0);
    const allChunks: SessionChunk[] = [];

    for (const msg of dbMessages) {
      const chunks = chunkMessage(msg.content, msg.id);
      allChunks.push(...chunks);
    }

    if (allChunks.length > 0) {
      const texts = allChunks.map(c => c.text);
      const vectors = this.embeddingProvider!.embedBatch
        ? await this.embeddingProvider!.embedBatch(texts, 'document')
        : await Promise.all(texts.map(t => this.embeddingProvider!.embed(t, 'document')));

      const points = allChunks.map((chunk, i) => {
        const msg = dbMessages.find(m => m.id === chunk.messageId)!;
        return {
          id: chunkPointId(chunk.messageId, chunk.chunkIndex),
          vector: vectors[i],
          payload: {
            message_id: chunk.messageId,
            session_id: session.id,
            agent_token_id: agentTokenId,
            role: msg.role,
            message_index: msg.messageIndex,
            chunk_index: chunk.chunkIndex,
            total_chunks: chunk.totalChunks,
            has_tool_use: msg.hasToolUse,
            tool_names: msg.toolNames,
          },
        };
      });

      await this.vectorStore!.upsertBatch('session_messages', points);
    }

    logger.info({ sessionId: session.id, chunks: allChunks.length }, 'Session vectors stored');
  }

  async listSessions(agentTokenId: string, filters: SessionFilters): Promise<Session[]> {
    return this.storage.listSessions(agentTokenId, filters);
  }

  async readSession(sessionId: string, agentTokenId: string, from?: number, to?: number): Promise<{
    session: Session;
    messages: SessionMessage[];
  } | null> {
    const session = await this.storage.getSession(sessionId);
    if (!session) return null;
    if (session.agentTokenId !== agentTokenId) throw new Error('Access denied: not your session');

    const messages = await this.storage.getMessages(sessionId, from ?? 0, to);
    return { session, messages };
  }

  async searchSessions(agentTokenId: string, query: string, options?: {
    projectId?: string;
    limit?: number;
  }): Promise<Array<Session & { score: number }>> {
    if (!this.embeddingProvider?.isReady() || !this.vectorStore) return [];

    const queryVector = await this.embeddingProvider.embed(query, 'query');
    const filter: VectorFilter = {
      must: [{ key: 'agent_token_id', match: { value: agentTokenId } }],
    };
    if (options?.projectId) {
      filter.must!.push({ key: 'project_id', match: { value: options.projectId } });
    }

    const results = await this.vectorStore.search('sessions', queryVector, filter, options?.limit ?? 10);

    const sessions = await Promise.all(
      results.map(async r => {
        const session = await this.storage.getSession(r.payload.session_id as string);
        return session ? { ...session, score: r.score } : null;
      }),
    );

    return sessions.filter((s): s is Session & { score: number } => s !== null);
  }

  async searchMessages(agentTokenId: string, query: string, options?: {
    sessionId?: string;
    limit?: number;
  }): Promise<Array<{ messageId: string; sessionId: string; role: string; score: number; chunkIndex: number; messageIndex: number }>> {
    if (!this.embeddingProvider?.isReady() || !this.vectorStore) return [];

    const queryVector = await this.embeddingProvider.embed(query, 'query');
    const filter: VectorFilter = {
      must: [{ key: 'agent_token_id', match: { value: agentTokenId } }],
    };
    if (options?.sessionId) {
      filter.must!.push({ key: 'session_id', match: { value: options.sessionId } });
    }

    const results = await this.vectorStore.search('session_messages', queryVector, filter, options?.limit ?? 10);

    return results.map(r => ({
      messageId: r.payload.message_id as string,
      sessionId: r.payload.session_id as string,
      role: r.payload.role as string,
      score: r.score,
      chunkIndex: (r.payload.chunk_index as number) ?? 0,
      messageIndex: (r.payload.message_index as number) ?? 0,
    }));
  }

  async deleteSession(sessionId: string, agentTokenId: string): Promise<boolean> {
    const result = await this.storage.deleteSession(sessionId, agentTokenId);

    if (this.vectorStore) {
      await this.vectorStore.delete('sessions', [sessionId]).catch(err =>
        logger.warn({ err, sessionId }, 'Failed to delete session vector'));
      await this.vectorStore.deleteByFilter('session_messages', {
        must: [{ key: 'session_id', match: { value: sessionId } }],
      }).catch(err =>
        logger.warn({ err, sessionId }, 'Failed to delete message vectors'));
    }

    return result;
  }
}
