-- Migration 004: Resize embedding column from vector(384) to vector(768)
-- Required for Gemini embedding models (gemini-embedding-001 outputs 768+ dims)
-- Invalidates any existing 384-dim embeddings — they will be re-generated by backfill on next startup

UPDATE entries SET embedding = NULL WHERE embedding IS NOT NULL;
ALTER TABLE entries ALTER COLUMN embedding TYPE vector(768);
